// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vtrdWLnKtv_XE8Bw2QASY0Ipe33U6aw',
    appId: '1:286937070787:web:b36a15b329b71c87f8f676',
    messagingSenderId: '286937070787',
    projectId: 'imageapp-82062',
    authDomain: 'imageapp-82062.firebaseapp.com',
    storageBucket: 'imageapp-82062.appspot.com',
    measurementId: 'G-WS1YX994H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTxX_LfHXKSI1YeEDNNeA6XiyvVm-cDE',
    appId: '1:286937070787:android:d84a877c41165de3f8f676',
    messagingSenderId: '286937070787',
    projectId: 'imageapp-82062',
    storageBucket: 'imageapp-82062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qoSlrZkT6AVlrHo4BImD3txkcGNoFb4',
    appId: '1:286937070787:ios:a16620d51867701cf8f676',
    messagingSenderId: '286937070787',
    projectId: 'imageapp-82062',
    storageBucket: 'imageapp-82062.appspot.com',
    iosBundleId: 'com.example.imageapp',
  );
}
